#version: '3.7'
#services:
#  postgres:
#    image: postgres:10.5
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    logging:
#      options:
#        max-size: 10m
#        max-file: "3"
#    ports:
#      - '5438:5432'
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#      - ./database/create_tables.database:/docker-entrypoint-initdb.d/create_tables.database

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
  app :
    build: ./app/
    depends_on:
      - database