services:
  database:
    image: postgres
    hostname: database
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    volumes:
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
#  api :
#    build: ./api/
#    depends_on:
#      - database
#  analysis :
#    build: ./analysis/
#    ports:
#      - 8501:8501
  app:
    build: ./app/
    depends_on:
      - database
    ports:
      - 8501:8501